### ISSUE TITLE
How to avoid the issue of CUDA out of memory?

### ISSUE THREAD

**Issue by sunxin000** [calubkk/RAAT#3]
Hello,

I found your paper very interesting. However, when I run the code, I encounter the  "CUDA out of memory" error, even with four 80G A100 GPUs. Do I need to implement mixed precision operations? Could you please provide your accelerate configuration? That would be very helpful. Thank you so much!

**Comment by calubkk** [comment]
Thank you for your interest in our work. Here is the configuration.
![image](https://github.com/user-attachments/assets/d25d965a-9afa-4cdf-94d6-8ecc93857354)
You can also use ‘accelerate config’ command to implement deepspeed.
![image](https://github.com/user-attachments/assets/569f83b3-497d-4883-8a3a-20aa5c63e2e4)
